### ISSUE TITLE
Doesn't work with Yarn installation

### ISSUE THREAD

**Issue by legendecas** [midwayjs/pandora#187]
Command `pandora start --name dashboard $(pandora-dashboard-dir)` and any other `pandora start` in app directory failed with error:

```
2018-03-05 14:06:27,396 ERROR 2267 nodejs.AssertionError [ERR_ASSERTION]: should setup current environment before using it
    at EnvironmentUtil.getCurrentEnvironment (~/.config/yarn/global/node_modules/pandora-env/src/EnvironmentUtil.ts:22:5)
    at new MetricsClient (~/.config/yarn/global/node_modules/pandora-metrics/src/MetricsClient.ts:13:60)
    at Function.getInstance (~/.config/yarn/global/node_modules/pandora-metrics/src/MetricsClient.ts:17:23)
    at Function.injectProcessMonitor (~/.config/yarn/global/node_modules/pandora/src/monitor/MonitorManager.ts:64:28)
    at ProcessBootstrap.injectMonitor (~/.config/yarn/global/node_modules/pandora/src/application/ProcessBootstrap.ts:114:20)
    at ProcessBootstrap.startAsWorker (~/.config/yarn/global/node_modules/pandora/src/application/ProcessBootstrap.ts:81:10)
    at ProcessBootstrap.start (~/.config/yarn/global/node_modules/pandora/src/application/ProcessBootstrap.ts:49:16)
    at Function.cmd (~/.config/yarn/global/node_modules/pandora/src/application/ProcessBootstrap.ts:180:22)
    at cmd (~/.config/yarn/global/node_modules/pandora/src/application/ProcessBootstrap.ts:202:20)
    at Object.<anonymous> (~/.config/yarn/global/node_modules/pandora/src/application/ProcessBootstrap.ts:208:3)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Function.Module.runMain (module.js:703:10)
generatedMessage: false
name: 'AssertionError [ERR_ASSERTION]'
code: 'ERR_ASSERTION'
actual: undefined
expected: true
operator: '=='
pid: 2267
```

Pandora version:
```
---------------------------------------------------------------------------

        ____                     __                          _
       / __ \ ____ _ ____   ____/ /____   _____ ____ _      (_)_____
      / /_/ // __ `// __ \ / __  // __ \ / ___// __ `/     / // ___/
     / ____// /_/ // / / // /_/ // /_/ // /   / /_/ /_    / /(__  )
    /_/     \__,_//_/ /_/ \__,_/ \____//_/    \__,_/(_)__/ //____/
                                                      /___/

---------------------------------------------------------------------------
                                                                   @Alibaba

BaseDir: ~
Pandora: 1.8.6 (~/.config/yarn/global/node_modules/pandora/bin)
Node: v9.7.1
```

Version 1.8.5 works normally.

**Comment by guangwong** [comment]
Did you installed it with yarn ?

**Comment by legendecas** [comment]
@guangwong yes, it's installed with `yarn global add pandora`

**Comment by pengliheng** [comment]
the same with me，and it can't
 Work
