### ISSUE TITLE
Node v8.0.0 - v8.2.0 isn't supported?

### ISSUE THREAD

**Issue by g0ne150** [midwayjs/pandora#197]
When i try to run `pandora start`, I got error:
```
TypeError: async_hooks.executionAsyncId is not a function
    at AsyncHook.init (/home/node/lib/node_modules/pandora/node_modules/cls-hooked/context.js:291:32)
    at init (async_hooks.js:444:43)
    at emitInitS (async_hooks.js:314:3)
    at new Timeout (timers.js:592:5)
    at createRepeatTimeout (timers.js:561:15)
    at exports.setInterval (timers.js:553:10)
    at TraceManager.timeoutCheck (/home/node/lib/node_modules/pandora/node_modules/pandora-metrics/src/trace/TraceManager.ts:35:19)
    at new TraceManager (/home/node/lib/node_modules/pandora/node_modules/pandora-metrics/src/trace/TraceManager.ts:25:10)
    at Function.getInstance (/home/node/lib/node_modules/pandora/node_modules/pandora-metrics/src/trace/TraceManager.ts:19:23)
    at TraceIndicator (/home/node/lib/node_modules/pandora/node_modules/pandora-metrics/src/indicator/impl/TraceIndicator.ts:17:84)
2018-03-09 17:11:35,532 INFO 19699 Process [name = worker, pid = 4315] Exit with code 1 and signal null
```

My node version is `v8.1.2`.

So I looked up node documentation for the api `async_hooks.executionAsyncId`. Looks like it is been renamed from `currentId` since `v8.2.0`.
![image](https://user-images.githubusercontent.com/8351695/37200424-b5ffa6cc-23bf-11e8-846b-6b00124e43e5.png)

Does it means Node `v8.0.0 - v8.2.0`(v8.2.0 is NOT included) is not supported?

**Comment by guangwong** [comment]
@mariodu confirm...

**Comment by mariodu** [comment]
The latest version of cls-hooked uses async_hooks API when run in Node >= 8.2.1. We use this module to implement continuation-local storage. So, we will fixed the version requirements in our documents. I'm sorry to make you wonder.

**Comment by mariodu** [comment]
And, are there any troubles when you upgrade Node.js version?

**Comment by g0ne150** [comment]
@mariodu There isn't any, thanks.
