### ISSUE TITLE
1.8.17 版本运行报错，之前的版本是可以的

### ISSUE THREAD

**Issue by myfjdthink** [midwayjs/pandora#219]
之前能正常运行的，更新版本后报错：
```
2018-04-10 16:39:24,617 ERROR 51639 { stack: 'Error: Cannot found any clients by selector: {"objectName":"__PANDORA_HUB_CONFIG_MANAGER"}\n    at Hub.handleMessageIn (/usr/local/lib/node_modules/.pandora_npminstall/pandora-hub/1.8.11/pandora-hub/dist/hub/Hub.js:70:23)\n    at emitThree (events.js:136:13)\n    at Server.emit (events.js:217:7)\n    at Server.MessengerBase.on (/usr/local/lib/node_modules/.pandora_npminstall/pandora-messenger/1.8.6/pandora-messenger/dist/base.js:19:22)\n    at emitThree (events.js:136:13)\n    at Server.emit (events.js:217:7)\n    at Server._handleMessage (/usr/local/lib/node_modules/.pandora_npminstall/pandora-messenger/1.8.6/pandora-messenger/dist/server.js:69:14)\n    at Client.client.on (/usr/local/lib/node_modules/.pandora_npminstall/pandora-messenger/1.8.6/pandora-messenger/dist/server.js:85:18)\n    at emitTwo (events.js:131:20)\n    at Client.emit (events.js:214:7)',
  message: 'Cannot found any clients by selector: {"objectName":"__PANDORA_HUB_CONFIG_MANAGER"}' }
2018-04-10 16:39:24,618 ERROR 51639 An error occurred during the start of ProcessBootstrap.
```

**Comment by guangwong** [comment]
你是否之前有 Pandora Daemon 进程一直没关过。 尝试 pandora exit 后再试试看。

**Comment by myfjdthink** [comment]
pandora exit 后问题解决
