### ISSUE TITLE
本地启动pandora报错

### ISSUE THREAD

**Issue by Congeek** [midwayjs/pandora#220]
procfile.js:
````
'use strict';

module.exports = (pandora) => {

  pandora
    .cluster('./app/app.js');
    
  /** 
  * you can custom workers scale number
  */
  // pandora
  //   .process('worker')
  //   .scale(2); // .scale('auto') means os.cpus().length

  /**
   * you can also use fork mode to start application 
   */
  // pandora
  //   .fork('app', './app.js');

  /**
   * you can create another process here
   */
  // pandora
  //   .process('background')
  //   .nodeArgs(['--expose-gc']);

  /**
   * more features please visit our document.
   * https://github.com/midwayjs/pandora/
   */

};
````

pandora dev 运行后
报错日志如下，app.js第一行import提示错误

````
2018-04-10 17:33:04,503 ERROR 58779 nodejs.SyntaxError: Unexpected token import
(function (exports, require, module, __filename, __dirname) { import express from 'express';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Module._compile (/usr/local/lib/node_modules/pandora/node_modules/pandora-metrics/node_modules/module-hook/src/lib/ModuleHook.ts:203:24)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at ClusterService.start (/usr/local/lib/node_modules/pandora/src/application/ProcfileReconcilerAccessor.ts:118:31)

pid: 58779
hostname: zhujiecongdeMacBook-Pro.local

2018-04-10 17:33:04,504 ERROR 58779 An error occurred during the start of ProcessBootstrap.
2018-04-10 17:33:04,506 INFO 58779 Process [name = worker, pid = 58779] Receive a signal SIGTERM, start to stopping, pid 58779
2018-04-10 17:33:04,516 INFO 58777 Process [name = worker, pid = 58779] Exit with code 0 and signal null
Error: Start failed! Run command [ pandora log frontend_service ] to get more information
````

**Comment by myfjdthink** [comment]
import 是 es6 的新语法，当前 node 版本不支持，你需要做 Babel 转译。
你直接运行 `node ./app/app.js` 估计也是不行的。

**Comment by czy88840616** [comment]
楼上说的对 import 的特性我们也是在 ts 中才使用，js 还是用回 require 吧。。
