### ISSUE TITLE
TypeScript环境下配置'Cannot read property 'dependencies' of undefined'

### ISSUE THREAD

**Issue by sultra** [midwayjs/pandora#252]
pandora 1.8.26 全局安装
IDE: vs code

安装官网的[说明](http://www.midwayjs.org/pandora/zh-cn/other/typescript.html) 配置了 **procfile.js**
 修改了启动程序的入口而已， 用dev方式启动

提示 **dependencies** 未定义！

```
2018-06-06 17:43:15,403 ERROR 32402 nodejs.TypeError: Cannot read property 'dependencies' of undefined
    at ProcfileReconciler.getServicesByCategory (~/node_modules/pandora/src/application/ProcfileReconciler.ts:309:68)
    at ProcessBootstrap.startAsWorker (~/node_modules/pandora/src/application/ProcessBootstrap.ts:92:63)
    at <anonymous>
```

请问怎么情况？
奇怪的是如果使用 pandora.cluster() 或者 pandora.fork() 就没问题！

---------------- 分割线 ---------------
在项目中使用 dorapan ，但是并没有TS的声明文件支持，难道在TS项目中只能 直接使用 ‘pandora’？
希望文档有个更具体点的使用TS说明！

**Comment by czy88840616** [comment]
@guangwong 看看

**Comment by guangwong** [comment]
1. 你的 procfile.js 可以提供一个看看吗？ （敏感信息可以打马）

2. dorapan 主要是没找到什么好的方法同步这些类型信息，这个问题还没找到好的解决方法。

**Comment by sultra** [comment]
procfile.js 就是按官方说明写的，如下

``` javascript
'use strict';

module.exports = (pandora) => {

  // pandora
  //   .fork('therole', './app/app.js');
  if (pandora.dev) {
     // 在 worker 定义中增加 -r ts-node/register
    pandora.process('worker').nodeArgs(['-r', 'ts-node/register', '--trace-warnings']);

     // 标识从源码目录启动
    pandora.service('core-config', './src/bin/www.ts').process('worker');
  }else{
    // 标识从编译后的目录启动
    // pandora.service('core-config', './dist/bin/www.js').process('worker');
  }

};
```

**Comment by guangwong** [comment]
./src/bin/www.ts 是不是导出的不是一个 Class ?
