### ISSUE TITLE
pandora 启动时候报错 Invalid or unexpected token

### ISSUE THREAD

**Issue by clancytom** [midwayjs/pandora#255]
###  在windows 下面启动，报错如下
```
F:\code\dev-server>pandora start
Starting dev-server at F:\code\dev-server
dev-server started failed, Error: Command failed: C:\nodejs\node.exe 
 -e 'require("C:\Users\g\AppData\Roaming\npm\node_modules\pandora\dist\application\ProcfileReconciler.js").ProcfileReconciler.echoStructure({"appName":"dev-server","appDir":"F:\\code\\dev-server"}, 
"C:\\Users\\G00318~1\\AppData\\Local\\Temp\\8b4cbb8d-53b3-4df3-afc7-2ca4bf9647ef"); process.exit()'
[eval]:1
'require(C:\Users\g00318677\AppData\Roaming\npm\node_modules\pandora\dist\application\ProcfileReconciler.js).ProcfileReconciler.echoStructure({appName:dev-server,appDir:F:\\code\\dev-server},
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:635:30)
    at evalScript (bootstrap_node.js:462:27)
    at startup (bootstrap_node.js:163:9)
    at bootstrap_node.js:608:3
```

这里的报错看不懂是什么问题导致的

**Comment by clancytom** [comment]
@guangwong 

```bash
$ pandora start
```

**Comment by clancytom** [comment]
### 还有个问题，我在linux机器上面，启动了pandora
```js
@SZV1000006663:~> pandora list
╔═══════════╤═══════╤══════════════════════════════════════════════════════════════════════════╤═════════╤════════════╤═══════════════╗
║ AppName   │ PID   │ AppDir                                                                   │ State   │ Uptime     │ Restart Count ║
╟───────────┼───────┼──────────────────────────────────────────────────────────────────────────┼─────────┼────────────┼───────────────╢
║ dashboard │ 87451 │ /home/wbfu/node/node-v8.9.1-linux-x64/lib/node_modules/pandora-dashboard │ Running │ 181766.654 │ 0             ║
╚═══════════╧═══════╧══════════════════════════════════════════════════════════════════════════╧═════════╧════════════╧═══════════════╝

```
```js
@SZV1000006663:~> netstat -anp |grep 9081
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:9081          0.0.0.0:*               LISTEN      87451/node
```
> 9081端口监听也是正常，但是页面上无法访问
![image](https://user-images.githubusercontent.com/25688775/41969823-4662c59c-7a3b-11e8-80af-b8a49a97c563.png)

**Comment by guangwong** [comment]
默认是监听在 127.0.0.1 端口的，你可以参考 https://github.com/midwayjs/pandora-dashboard#custom-tcp-port-and-ip-address。

把 HOST 设置成 DASHBOARD_HOST=0.0.0.0，这样所有端口都能访问了

**Comment by clancytom** [comment]
@guangwong  第一个问题，能看出来是哪里报的错吗

**Comment by clancytom** [comment]
@guangwong  可以了
第一个问题，能帮我看下是哪里出的问题了吗

**Comment by guangwong** [comment]
第一个问题，是因为我们不支持 windows ...

**Comment by ta7sudan** [comment]
请问WSL也不支持吗? 目前Win10 64 1809下, 最新的WSL Ubuntu, 也无法启动, 尽管没有提示任何错误, 但是会一直卡在这里, 并且实际上守护进程并没有启动
```
Daemon [ pid = 556 ] Started successfully.
```

**Comment by guangwong** [comment]
@ta7sudan 等我试一下回复您，这个没有实验过。
