### ISSUE TITLE
Could not found service id

### ISSUE THREAD

**Issue by zimtsui** [midwayjs/pandora#274]
@guangwong @czy88840616 
最基础的代码，这个dependencies似乎不能找到诶……O(∩_∩)O谢谢
procfile.js
```js
export default (pandora) => {
    pandora.process('process1');
    pandora.process('process2');
    pandora
        .service('service1', './service1.js')
        .process('process1');
    pandora
        .service('service2', './service2.js')
        .process('process2')
        .dependency([
            'service1',
        ]);
};
```
service1.js
```js
const Service1 = class {
    async start() {
        console.log('service1 started');
    }

    async stop() {
        console.log('service1 stopped');
    }
};

export default Service1;
```
service2.js
```js
const Service2 = class {
    async start() {
        console.log('service2 started');
    }

    async stop() {
        console.log('service2 stopped');
    }
};

export default Service2;
```
output
```shell
service1 started
2018-10-26 23:24:55,715 INFO 30378 Process [name = process1, pid = 30397] Started successfully!
2018-10-26 23:24:56,069 ERROR 30404 nodejs.AssertionError [ERR_ASSERTION]: Could not found service id: service1
    at ServiceReconciler.getWeight (/usr/local/lib/node_modules/pandora/src/service/ServiceReconciler.ts:82:5)
    at ServiceReconciler.getWeight (/usr/local/lib/node_modules/pandora/src/service/ServiceReconciler.ts:90:36)
    at ServiceReconciler.getOrderedServiceIdSet (/usr/local/lib/node_modules/pandora/src/service/ServiceReconciler.ts:55:34)
    at ServiceReconciler.instantiate (/usr/local/lib/node_modules/pandora/src/service/ServiceReconciler.ts:100:29)
    at ServiceReconciler.start (/usr/local/lib/node_modules/pandora/src/service/ServiceReconciler.ts:150:10)
    at ProcessContext.start (/usr/local/lib/node_modules/pandora/src/application/ProcessContext.ts:78:34)
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: false
expected: true
operator: "=="
pid: 30404
hostname: x1c

2018-10-26 23:24:56,070 ERROR 30404 An error occurred during the start of ProcessBootstrap.
2018-10-26 23:24:56,072 INFO 30404 Process [name = process2, pid = 30404] Receive a signal SIGTERM, start to stopping, pid 30404
2018-10-26 23:24:56,079 INFO 30378 Process [name = process2, pid = 30404] Exit with code 0 and signal null
2018-10-26 23:24:56,080 INFO 30397 Process [name = process1, pid = 30397] Receive a signal SIGTERM, start to stopping, pid 30397
service1 stopped
2018-10-26 23:24:56,091 INFO 30378 Process [name = process1, pid = 30397] Exit with code 0 and signal null
Error: Start failed! Run command [ pandora log learnpandora ] to get more information
```

**Comment by czy88840616** [comment]
service设计之初是为了内部场景....这得@guangwong 来解惑了
Zim <notifications@github.com>于2018年10月26日 周五下午11:37写道：

**Comment by zimtsui** [comment]
之前代码贴错了，改了一下O(∩_∩)O

**Comment by guangwong** [comment]
原因应该是 Service 没法跨进程描述依赖。

**Comment by zimtsui** [comment]
> 原因应该是 Service 没法跨进程描述依赖。

那么建议在文档中提示一下
