### ISSUE TITLE
启动报错：should setup current environment before using it

### ISSUE THREAD

**Issue by ruanzhijun** [midwayjs/pandora#278]
根据 pandora 的特性，我写了一个链路跟踪的包，[https://www.npmjs.com/package/share-tracer](https://www.npmjs.com/package/share-tracer)，[github地址](https://github.com/share-group/share-tracer)，但是在应用启动的时候，报 should setup current environment before using it。这份代码，在本地开发环境(windows)是正常的，服务器centos 7.2不正常。另外我有一个生产级的项目也接入了这个包，开发生产环境都可以正常使用(ubuntu 1604)。

  AssertionError [ERR_ASSERTION]: should setup current environment before using it
     at EnvironmentUtil.getCurrentEnvironment (/install/MY_APP/node_modules/pandora-hook/node_modules/pandora-env/dist/EnvironmentUtil.js:17:9)
     at new Patcher (/install/MY_APP/node_modules/pandora-hook/node_modules/pandora-metrics/dist/trace/Patcher.js:12:64)
     at new HttpServerPatcher (/install/MY_APP/node_modules/pandora-hook/dist/patch/HttpServer.js:12:9)
     at new HttpServerPatcher (/install/MY_APP/node_modules/share-tracer/dist/lib/HttpServerPatcher.js:5:1)
     at ShareTracer.run (/install/MY_APP/node_modules/share-tracer/dist/ShareTracer.js:17:9)
     at Object.<anonymous> (/install/MY_APP/app/common/bootstrap/tracer.js:16:59)
     at Module._compile (internal/modules/cjs/loader.js:707:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
     at Module.load (internal/modules/cjs/loader.js:605:32)
     at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
     at Function.Module._load (internal/modules/cjs/loader.js:536:3)
     at Module.require (internal/modules/cjs/loader.js:643:17)
     at require (internal/modules/cjs/helpers.js:22:18)
     at Object.<anonymous> (/install/MY_APP/app/common/bootstrap/index.js:7:10)
     at Module._compile (internal/modules/cjs/loader.js:707:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)

请指明一下方向！谢谢！

**Comment by czy88840616** [comment]
https://github.com/midwayjs/pandora/blob/master/packages/metrics/test/TestHelper.ts#L9

启动的时候应该没注册环境，可以像上面的测试那样注册一个。

**Comment by ruanzhijun** [comment]
有的在 ShareTracer 的构造函数里面注册了。
[https://github.com/share-group/share-tracer/blob/master/src/ShareTracer.ts#L30](https://github.com/share-group/share-tracer/blob/master/src/ShareTracer.ts#L30)

**Comment by guangwong** [comment]
你的包是怎么装的，现在有些单例比较依赖 npm 的软链机制。比如版本依赖不同、或者link 等情况有可能搞出来两个 EnvironmentUtil 实例？

**Comment by guangwong** [comment]
@ruanzhijun yarn 的确是会有问题，你换成 npm 应该就能解决。 下个版本重构掉，不这样搞了。

**Comment by ruanzhijun** [comment]
@guangwong   果然！ 谢谢了！
