### ISSUE TITLE
pandora.service is not a function

### ISSUE THREAD

**Issue by ddzyan** [midwayjs/pandora#304]
我遇到了如下的问题，请问要如何解决？操作步骤如下：
操作系统ubuntu

```sh
node -v
v10.16.0

npm -v
6.10.3

cnpm i pandora -g

cnpm i pandora-dashboard -g

pandora start --name dashboard `pandora-dashboard-dir`
[Pandora.js] Error: Command failed: /home/ddz/.nvm/versions/node/v10.16.0/bin/node  -e 'require("/home/ddz/.nvm/versions/node/v10.16.0/lib/node_modules/pandora/dist/application/ProcfileReconciler.js").ProcfileReconciler.echoStructure({"appDir":"/home/ddz/.nvm/versions/node/v10.16.0/lib/node_modules/pandora-dashboard","appName":"dashboard"}, "/tmp/41e3af1b-465a-404b-8cc1-d9b295d21309"); process.exit()'
/home/ddz/.nvm/versions/node/v10.16.0/lib/node_modules/pandora-dashboard/procfile.js:7
    pandora.service('dashboard', './dist/Dashboard').process('worker');
            ^

TypeError: pandora.service is not a function
    at module.exports (/home/ddz/.nvm/versions/node/v10.16.0/lib/node_modules/pandora-dashboard/procfile.js:7:13)
    at ProcfileReconciler.callProcfile (/home/ddz/.nvm/versions/node/v10.16.0/lib/node_modules/pandora/dist/application/ProcfileReconciler.js:81:13)
    at ProcfileReconciler.discover (/home/ddz/.nvm/versions/node/v10.16.0/lib/node_modules/pandora/dist/application/ProcfileReconciler.js:65:18)
    at Function.echoStructure (/home/ddz/.nvm/versions/node/v10.16.0/lib/node_modules/pandora/dist/application/ProcfileReconciler.js:191:28)
    at [eval]:1:133
    at Script.runInThisContext (vm.js:122:20)
    at Object.runInThisContext (vm.js:329:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at evalScript (internal/bootstrap/node.js:589:27)

Error: Command failed: /home/ddz/.nvm/versions/node/v10.16.0/bin/node  -e 'require("/home/ddz/.nvm/versions/node/v10.16.0/lib/node_modules/pandora/dist/application/ProcfileReconciler.js").ProcfileReconciler.echoStructure({"appDir":"/home/ddz/.nvm/versions/node/v10.16.0/lib/node_modules/pandora-dashboard","appName":"dashboard"}, "/tmp/41e3af1b-465a-404b-8cc1-d9b295d21309"); process.exit()'
/home/ddz/.nvm/versions/node/v10.16.0/lib/node_modules/pandora-dashboard/procfile.js:7
    pandora.service('dashboard', './dist/Dashboard').process('worker');
            ^

TypeError: pandora.service is not a function
    at module.exports (/home/ddz/.nvm/versions/node/v10.16.0/lib/node_modules/pandora-dashboard/procfile.js:7:13)
    at ProcfileReconciler.callProcfile (/home/ddz/.nvm/versions/node/v10.16.0/lib/node_modules/pandora/dist/application/ProcfileReconciler.js:81:13)
    at ProcfileReconciler.discover (/home/ddz/.nvm/versions/node/v10.16.0/lib/node_modules/pandora/dist/application/ProcfileReconciler.js:65:18)
    at Function.echoStructure (/home/ddz/.nvm/versions/node/v10.16.0/lib/node_modules/pandora/dist/application/ProcfileReconciler.js:191:28)
    at [eval]:1:133
    at Script.runInThisContext (vm.js:122:20)
    at Object.runInThisContext (vm.js:329:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at evalScript (internal/bootstrap/node.js:589:27)

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12)
```

**Comment by ddzyan** [comment]
项目还有人维护嘛

**Comment by waitingsong** [comment]
换 npm 安装执行试试？

**Comment by ddzyan** [comment]
> 换 npm 安装执行试试？

我已经试过了，还是出现上面的问题，你们不会按照上面的操作不会出现报错嘛

**Comment by guangwong** [comment]
这是 1.0 的还是 2.0 的？

**Comment by guangwong** [comment]
pandora-dashboard-dir 是向 pandora 1.0 配套的，2.0 不支持； 然后 2.0 现在文档不是很完善，要配套 Sandbox 来做集群监控；

**Comment by ddzyan** [comment]
> pandora-dashboard-dir 是向 pandora 1.0 配套的，2.0 不支持； 然后 2.0 现在文档不是很完善，要配套 Sandbox 来做集群监控；
好的，我现在修改了安装版本后，成功了
```sh
npm i pandora@1.10.6 -g 
```
因为现在文档不全，我可以理解为2.0版本还无法使用对吗

**Comment by czy88840616** [comment]
@ddzyan 2.0 应该能用，但是没有文档。
